import {gemini,constraints} from '@/lib/gemini';
import {validatePlan,validateScenes} from '@/lib/workflow';
export async function POST(request:Request){
 const headers={'Cache-Control':'no-store'};
 try{
 if(request.headers.get('origin')&&new URL(request.headers.get('origin')!).origin!==new URL(request.url).origin)return Response.json({error:'Request origin not allowed.'},{status:403,headers});
 const raw=await request.text();if(raw.length>15000000)return Response.json({error:'Files exceed the 10 MB total upload limit.'},{status:413,headers});
 const {key,model,question,scenes,history}=JSON.parse(raw);validateScenes(scenes);
 if(typeof key!=='string'||!key.trim()||typeof model!=='string'||!/^gemini-[a-z0-9.-]+$/.test(model)||typeof question!=='string'||!question.trim()||question.length>4000)return Response.json({error:'Connect Gemini and enter a question of up to 4,000 characters.'},{status:400,headers});
 const prompt=`${constraints} You are the input verification and workflow planner for SatQuery AI. The user uploads 1 or more files and asks a natural-language question. They NEVER select a mode. Inspect ALL supplied images and the question. Compose the minimum appropriate workflow from scene (single or multi-scene description/grounding), temporal (change across dated acquisitions), fusion (sensor-specific interpretation and evidence fusion). A request may need several in sequence. Do not force unrelated images into a pair. Record each input's likely sensor and acquisition date, distinguishing documented/user-supplied information from inference and unknown. Dates can be unknown for scene description. If temporal order, shared region, or sensor identity is essential but uncertain, ask ONE concise clarification; do not proceed to unsupported change/fusion conclusions. Unknown georeferencing alone need not block qualitative scene description. For requests needing original bands or GIS operations unavailable here, explain that limitation and ask whether qualitative interpretation would help. checks must be honest visual/input checks, not claimed computed GIS verification. Return ONLY JSON {"title":"selected workflow short title","rationale":"why this plan fits these files and question","workflows":["scene"],"inputs":[{"image":0,"sensor":"Optical likely / SAR user-supplied / Unknown","date":"Unknown or source","assessment":"input suitability and limits"}],"checks":[{"label":"short","status":"passed or uncertain or blocked","detail":"what was assessed and evidence"}],"steps":["visual interpretation steps this prototype can perform"],"clarification":null}. Include exactly one inputs item per image (indices 0 through ${scenes.length-1}). clarification is a question string when blocked or missing essential context, otherwise null. Question: ${question}. Files (unverified metadata): ${JSON.stringify(scenes.map(({data,...s})=>s))}. Prior conversation: ${JSON.stringify(Array.isArray(history)?history.slice(-8):[]).slice(0,18000)}`;
 const plan=validatePlan(await gemini(key,model,prompt,scenes,request.signal),scenes.length);
 return Response.json(plan,{headers});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Input verification failed. Please retry.'},{status:400,headers});}
}
