import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const urls={};
const compile=path=>ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const moduleURL=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
for(const name of ['analysis','workflow','gemini'])urls['@/lib/'+name]=moduleURL(compile('lib/'+name+'.ts'));
function route(path){return import(moduleURL(compile(path).replace(/'(@\/lib\/[^']+)'/g,(_,name)=>JSON.stringify(urls[name]))));}
const {sampleAnalysis,validateAnalysis}=await import(urls['@/lib/analysis']);
const {samplePlan,validatePlan,validateScenes}=await import(urls['@/lib/workflow']);
const {POST:analyze}=await route('app/api/analyze/route.ts');
const {POST:plan}=await route('app/api/plan/route.ts');
const img={name:'scene.png',label:'',mime:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD7sAAAAASUVORK5CYII='};
const valid={key:'test-key',model:'gemini-2.5-flash',question:'What is visible?',scenes:[img],plan:samplePlan('Describe the scene')};
const request=body=>new Request('http://localhost/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const output=value=>Response.json({candidates:[{content:{parts:[{text:JSON.stringify(value)}]}}]});
test('Sample planner composes scene workflow and pauses change or measurements',()=>{assert.equal(samplePlan('Describe the vegetation').clarification,null);assert.match(samplePlan('What changed?').clarification,/separate/);assert.match(samplePlan('Calculate NDVI').clarification,/spectral/);});
test('One to six inputs, duplicate detection, and actual signatures',()=>{validateScenes([img]);assert.throws(()=>validateScenes([]));assert.throws(()=>validateScenes([img,img]),/Duplicate/);assert.throws(()=>validateScenes([{...img,mime:'image/jpeg'}]),/signature/);assert.throws(()=>validateScenes(Array(7).fill(img)));});
test('Mixed workflows are accepted without a user-selected mode',()=>{const p=samplePlan('Describe');p.workflows=['scene','temporal','fusion'];p.inputs.push({image:1,sensor:'SAR, user-supplied',date:'Unknown',assessment:'Needs context'});assert.deepEqual(validatePlan(p,2).workflows,['scene','temporal','fusion']);});
test('Missing inputs and blocked checks force clarification',()=>{const p=samplePlan('Describe');p.workflows=['temporal'];assert.ok(validatePlan(p,1).clarification);const q=samplePlan('Describe');q.checks[0].status='blocked';assert.ok(validatePlan(q,1).clarification);assert.throws(()=>validatePlan({...q,inputs:[]},1));});
test('Evidence on later images is retained; invalid boxes are rejected',()=>{const r=sampleAnalysis('Water');r.evidence.push({title:'Third scene',detail:'Reference',image:2,box:[10,10,30,30]},{title:'bad',detail:'bad',image:0,box:[90,0,10,100]});assert.equal(validateAnalysis(r).evidence.length,4);});
test('Blocked plan cannot reach the analysis provider',async()=>{const saved=globalThis.fetch;globalThis.fetch=()=>{throw Error('Must not call provider');};try{const r=await analyze(request({...valid,plan:samplePlan('What changed?')}));assert.equal(r.status,409);}finally{globalThis.fetch=saved;}});
test('Planner sees every image and returns a structured workflow',async()=>{const saved=globalThis.fetch;try{globalThis.fetch=async(url,options)=>{const sent=JSON.parse(options.body);assert.equal(sent.contents[0].parts.length,2);assert.match(sent.contents[0].parts[0].text,/NEVER select a mode/);return output(valid.plan);};const r=await plan(request(valid));assert.equal(r.status,200);assert.equal((await r.json()).title,valid.plan.title);}finally{globalThis.fetch=saved;}});
test('Analysis executes the selected plan and preserves source attribution',async()=>{const saved=globalThis.fetch;try{globalThis.fetch=async()=>output(sampleAnalysis('Water'));const r=await analyze(request(valid));assert.equal(r.status,200);assert.match((await r.json()).source,/Gemini/);}finally{globalThis.fetch=saved;}});
test('Quota errors and malformed plans never generate substitute findings',async()=>{const saved=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({error:'provider private data'},{status:429});const r=await analyze(request(valid));assert.equal(r.status,502);assert.match((await r.json()).error,/quota/);globalThis.fetch=async()=>output({title:'incomplete'});const p=await plan(request(valid));assert.equal(p.status,400);}finally{globalThis.fetch=saved;}});
