import {sampleAnalysis} from './analysis';
import {validatePlan,classifyIntent,type WorkflowPlan} from './workflow';
import type {CandidateBundle,Finding,EvidenceItem,MissionResult} from './domain';
import type {CapabilityRegistry} from './registry';
import {capabilities} from './domain';
export type DemoId='single'|'urban'|'flood';
export const missions=[
 {id:'urban' as DemoId,title:'Cairo: a changing city',subtitle:'1984 → 2019 · urban expansion',question:'What meaningful construction and vegetation changes occurred in this area?',images:[{url:'/missions/urban-before.jpg',name:'Cairo · 1984',label:'Optical Landsat 5, 1984-07-02, Cairo; same region as Image 2',date:'1984-07-02',sensor:'Landsat optical',kind:'optical'},{url:'/missions/urban-after.jpg',name:'Cairo · 2019',label:'Optical Landsat 8, 2019-09-05, Cairo; same region as Image 1',date:'2019-09-05',sensor:'Landsat optical',kind:'optical'}],credit:'NASA Earth Observatory / Lauren Dauphin; Landsat data from USGS.',source:'https://science.nasa.gov/earth/earth-observatory/new-ground-for-an-ancient-city-146521/'},
 {id:'flood' as DemoId,title:'Florence: incomplete agreement',subtitle:'Optical + radar-derived flood context',question:'Which areas show evidence of flooding across the optical and SAR-derived observations?',images:[{url:'/missions/flood-optical.jpg',name:'Trent River · optical',label:'Landsat 8 optical false-color 6-5-4, 2018-09-19; Trent River local view',date:'2018-09-19',sensor:'Landsat optical false-color',kind:'optical'},{url:'/missions/flood-sar-derived.jpg',name:'Florence · published flood proxy',label:'Sentinel-1 SAR-derived ARIA flood proxy, 2018-09-14; regional coast view, different footprint. Not raw SAR.',date:'2018-09-14',sensor:'Sentinel-1 SAR-derived map',kind:'sar'}],credit:'NASA Earth Observatory / Joshua Stevens & Lauren Dauphin; modified Copernicus Sentinel data (2018), ESA, NASA-JPL/Caltech ARIA; Landsat/USGS.',source:'https://science.nasa.gov/earth/earth-observatory/florence-inundates-the-carolinas-92775/',opticalSource:'https://science.nasa.gov/earth/earth-observatory/a-broad-view-of-flooding-in-the-carolinas-92786/'},
 {id:'single' as DemoId,title:'Sundarbans: read the landscape',subtitle:'Single archival observation',question:'What major land-cover and infrastructure features are visible?',images:[{url:'/satellite.jpg',name:'Sundarbans · Landsat mosaic',label:'Optical Landsat 7 mosaic, November 1999 and November 2000; no temporal pair',date:'1999–2000 mosaic',sensor:'Landsat optical',kind:'optical'}],credit:'NASA Earth Observatory / Jesse Allen; University of Maryland Global Land Cover Facility.',source:'https://science.nasa.gov/earth/earth-observatory/sundarbans-bangladesh-7028/'}
];
export function demoPlan(id:DemoId,question:string):WorkflowPlan{const mission=missions.find(m=>m.id===id)!;return validatePlan({title:id==='urban'?'Temporal candidates → evidence gate':id==='flood'?'Optical evidence → radar context → agreement check':'Scene understanding → evidence gate',rationale:id==='urban'?'The question asks about change across a source-published Cairo optical pair. Original dates are documented, but no independent registration is performed.':id==='flood'?'These published optical and radar-derived observations support complementary regional context. Their different dates and footprints prevent location-by-location confirmation.':'A single optical mosaic supports conservative scene description and visual references.',intent:question,intents:classifyIntent(question),inputs:mission.images.map((s,i)=>({image:i,sensor:s.sensor,sensorKind:s.kind,sensorSource:'provided',date:s.date,dateSource:'provided',assessment:s.label})),inferredRelationships:id==='single'?[]:[{imageA:'img-1',imageB:'img-2',relationship:id==='urban'?'temporal':'cross_sensor',confidence:id==='urban'?'high':'medium',basis:[id==='urban'?'NASA presents the Cairo acquisitions as a same-region pair.':'Source articles document different dates and footprints.'],verified:false}],clarificationQuestions:[],checks:[{label:'Geospatial alignment',status:'uncertain',detail:id==='flood'?'Different footprints; do not treat these as aligned evidence.':'No independent geometric alignment or quantitative measurement.'}]},mission.images.length,JSON.stringify({question,labels:mission.images.map(s=>s.label),history:[]}));}
function candidate(id:string,title:string,statement:string,category:string,regions:{imageId:string;x:number;y:number;width:number;height:number;description:string}[],low=false):CandidateBundle{
 const evidenceItems:EvidenceItem[]=regions.map((r,i)=>({id:`${id}-e${i+1}`,imageId:r.imageId,findingId:id,evidenceType:regions.length>1?'temporal_difference':'visual_region',description:r.description,region:{x:r.x,y:r.y,width:r.width,height:r.height},reliability:low?'low':'high',limitations:['Curated approximate reference, not model-generated segmentation.'],sourceStep:'fixture'}));
 const finding:Finding={id,title,statement,category,classification:low?'uncertain':'likely_interpretation',evidenceIds:evidenceItems.map(e=>e.id),confidence:{level:low?'low':'high',meaning:'Curated visual support, not calibrated accuracy.'},alternativeExplanations:low?['Seasonal vegetation, acquisition conditions or display differences may explain appearance.']:['Display resolution and registration remain unverified.'],limitations:['Illustrative reviewed fixture; not a live specialist model result.']};return {findings:[finding],evidenceItems,crossSensorAssessment:[]};
}
function combine(...b:CandidateBundle[]):CandidateBundle{return {findings:b.flatMap(x=>x.findings),evidenceItems:b.flatMap(x=>x.evidenceItems),crossSensorAssessment:b.flatMap(x=>x.crossSensorAssessment)};}
export function demoRegistry(id:DemoId):CapabilityRegistry{return Object.fromEntries(capabilities.map(capability=>[capability,{name:'Curated demo fixture · '+capability.replaceAll('_',' '),async execute(c:any){
 if(capability==='evidence_validation')return {validations:c.candidates.findings.map((f:Finding)=>({findingId:f.id,verdict:id==='flood'?'partially_supported':f.confidence.level==='low'?'insufficient':'supported',reasons:id==='flood'?['Different dates and geographic footprints prevent local cross-sensor confirmation.']:f.confidence.level==='low'?['Seasonal or acquisition differences cannot be excluded.']:['The highlighted regions visually support the qualified statement.'],recommendation:f.confidence.level==='low'?'Compare acquisitions from the same season with known alignment.':id==='flood'?'Obtain co-located, same-period optical and radar observations.':undefined}))};
 if(capability==='synthesis')return {directAnswer:id==='urban'?'The observations support apparent built-up expansion east of Cairo. Vegetation appearance also differs, but the imagery does not establish whether that difference is seasonal or a lasting land-cover change.':id==='flood'?'Optical imagery and the published radar-derived product both provide flood-related context, but their different footprints and dates do not confirm the same local areas.':'The mosaic shows branching waterways, dense vegetated areas, and a contrasting northern landscape. Specific infrastructure identities are not established.',uncertainties:['Curated demonstration using published images, not a live Gemini run.'],nextQuestion:id==='urban'?'Could the vegetation difference be seasonal?':'What additional evidence would resolve the uncertainty?'};
 if(['visual_grounding','uncertainty_check'].includes(capability))return c.candidates;
 if(id==='single'){const sample=sampleAnalysis('Describe');return combine(...sample.evidence.map((e,i)=>candidate('scene-'+i,e.title,e.detail,'land_cover',[{imageId:'img-1',x:e.box[0],y:e.box[1],width:e.box[2]-e.box[0],height:e.box[3]-e.box[1],description:e.detail}])));}
 if(id==='urban')return combine(candidate('construction','Apparent new built-up development','Geometric built-up patterns occupy areas east of Cairo that appear mostly open in the earlier observation.','construction',[{imageId:'img-1',x:63,y:43,width:29,height:31,description:'Earlier observation: largely open desert in the reference area.'},{imageId:'img-2',x:63,y:43,width:29,height:31,description:'Later observation: extensive geometric street and building-like patterns.'}]),candidate('vegetation','Vegetation appearance differs','Vegetation color and patch patterns differ in the northern part of the scene; lasting vegetation loss is not established.','vegetation_change',[{imageId:'img-1',x:3,y:3,width:29,height:25,description:'Earlier observation: vegetated field mosaic.'},{imageId:'img-2',x:3,y:3,width:29,height:25,description:'Later observation: a different field and vegetation appearance.'}],true));
 if(capability==='optical_analysis')return candidate('optical-water','Optical water-like surfaces','Dark surfaces near the Trent River are consistent with water in this published false-color view. Flood extent cannot be measured here.','flood_reasoning',[{imageId:'img-1',x:33,y:21,width:43,height:48,description:'Dark water-like areas around the Trent River and Trenton.'}]);
 if(capability==='sar_analysis')return candidate('radar-proxy','Published radar-derived flood proxy','Blue areas in the published ARIA product indicate likely flooding according to its source; this is not raw SAR or a SatQuery-generated map.','flood_reasoning',[{imageId:'img-2',x:30,y:8,width:39,height:45,description:'Regional blue proxy markings in the source-published map.'}]);
 const b=candidate('cross-context','Complementary evidence, not local confirmation','The observations provide complementary flood context, but their dates and footprints differ.','cross_sensor_confirmation',[{imageId:'img-1',x:33,y:21,width:43,height:48,description:'Local optical river context.'},{imageId:'img-2',x:30,y:8,width:39,height:45,description:'Regional radar-derived proxy context; not the same reference window.'}],true);b.crossSensorAssessment=[{finding:'Local flood confirmation',relationship:'inconclusive',explanation:'The selected regions are not co-located or simultaneous; the radar-derived map cannot confirm the precise optical region.',evidenceIds:b.evidenceItems.map(e=>e.id)}];return b;
 }}])) as CapabilityRegistry;}
export function reviewPlan(plan:WorkflowPlan):WorkflowPlan{const workflow=plan.workflow.filter(s=>['uncertainty_check','evidence_validation','synthesis'].includes(s.capability)).map((s,i,a)=>({...s,dependencies:i?[a[i-1].id]:[],status:'pending' as const}));return {...plan,title:'Review existing findings and alternatives',workflow,clarification:null,clarificationRequired:false,clarificationQuestions:[],steps:workflow.map(s=>s.title)};}
