import type {CandidateBundle,EvidenceValidation,MissionResult} from './domain';
function object(v:unknown):Record<string,any>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Malformed specialist response.');return v as Record<string,any>;}
function text(v:unknown){if(typeof v!=='string'||v.length>10000)throw Error('Malformed specialist text.');return v;}
function strings(v:unknown):string[]{if(!Array.isArray(v)||v.length>40||v.some(x=>typeof x!=='string'||x.length>4000))throw Error('Malformed specialist list.');return v;}
function member(v:unknown,values:string[]){if(typeof v!=='string'||!values.includes(v))throw Error('Unknown specialist classification.');return v;}
export function validateBundle(value:unknown,imageIds:string[],stepId:string):CandidateBundle{
 const v=object(value);if(!Array.isArray(v.findings)||!Array.isArray(v.evidenceItems)||v.findings.length>12||v.evidenceItems.length>24)throw Error('Malformed findings or evidence.');
 const findings=v.findings.map((item:unknown)=>{const f=object(item),c=object(f.confidence);return {id:text(f.id),title:text(f.title),statement:text(f.statement),category:typeof f.category==='string'?f.category:'visual',classification:member(f.classification,['observation','likely_interpretation','uncertain']),evidenceIds:strings(f.evidenceIds),confidence:{level:member(c.level,['high','medium','low']),meaning:'AI-assessed visual support; not calibrated model accuracy.'},alternativeExplanations:strings(f.alternativeExplanations),limitations:strings(f.limitations)};});
 const evidenceItems=v.evidenceItems.map((item:unknown)=>{const e=object(item);if(!imageIds.includes(e.imageId))throw Error('Evidence refers to an unavailable image.');let region;
 if(e.region!=null){const r=object(e.region);if(![r.x,r.y,r.width,r.height].every(Number.isFinite)||r.x<0||r.y<0||r.width<=0||r.height<=0||r.x+r.width>100||r.y+r.height>100)throw Error('Evidence coordinates are outside the image.');region={x:r.x,y:r.y,width:r.width,height:r.height};}
 return {id:text(e.id),imageId:e.imageId,findingId:text(e.findingId),evidenceType:member(e.evidenceType,['visual_region','temporal_difference','cross_sensor_support']),description:text(e.description),region,reliability:member(e.reliability,['high','medium','low']),limitations:strings(e.limitations),sourceStep:stepId};});
 if(new Set(findings.map((f:any)=>f.id)).size!==findings.length||new Set(evidenceItems.map((e:any)=>e.id)).size!==evidenceItems.length)throw Error('Duplicate finding or evidence IDs.');
 for(const f of findings)if(f.evidenceIds.some((id:string)=>!evidenceItems.some((e:any)=>e.id===id&&e.findingId===f.id)))throw Error('A finding references missing or unrelated evidence.');
 for(const e of evidenceItems)if(!findings.some((f:any)=>f.id===e.findingId&&f.evidenceIds.includes(e.id)))throw Error('Evidence is not linked to its finding.');
 const crossSensorAssessment=(v.crossSensorAssessment||[]).map((item:unknown)=>{const c=object(item);const ids=strings(c.evidenceIds);if(ids.some(id=>!evidenceItems.some((e:any)=>e.id===id)))throw Error('Cross-sensor evidence reference missing.');return {finding:text(c.finding),relationship:member(c.relationship,['agreement','complementary','disagreement','inconclusive']),explanation:text(c.explanation),evidenceIds:ids};});
 return {findings,evidenceItems,crossSensorAssessment} as CandidateBundle;
}
export function validateVerdicts(value:unknown,bundle:CandidateBundle,plan?:import("./workflow").WorkflowPlan):EvidenceValidation[]{
 const v=object(value);if(!Array.isArray(v.validations))throw Error('Evidence gate returned no verdicts.');
 const results=v.validations.map((item:unknown)=>{const e=object(item);return {findingId:text(e.findingId),verdict:member(e.verdict,['supported','partially_supported','insufficient','conflicting']),reasons:strings(e.reasons),recommendation:typeof e.recommendation==='string'?e.recommendation:undefined};}) as EvidenceValidation[];
 if(results.length!==bundle.findings.length||new Set(results.map(v=>v.findingId)).size!==results.length||results.some(v=>!bundle.findings.some(f=>f.id===v.findingId)))throw Error('Every finding must receive exactly one evidence verdict.');
 return results.map(v=>{const f=bundle.findings.find(f=>f.id===v.findingId)!;const refs=bundle.evidenceItems.filter(e=>f.evidenceIds.includes(e.id));if(!refs.length||!refs.some(e=>e.region))return {...v,verdict:'insufficient',reasons:[...v.reasons,'No locatable visual grounding supports this finding.']};const temporalSteps=plan?.workflow.filter(s=>s.capability==='temporal_comparison'&&(f.id.startsWith(s.id+'-')||refs.some(e=>e.sourceStep===s.id)))||[];if(temporalSteps.some(s=>s.inputImageIds.some(id=>!refs.some(e=>e.imageId===id&&e.region))))return {...v,verdict:'insufficient',reasons:[...v.reasons,'A temporal candidate lacks grounded evidence in both acquisitions.']};const contradiction=bundle.crossSensorAssessment.some(c=>c.relationship==='disagreement'&&c.evidenceIds.some(id=>f.evidenceIds.includes(id)));if(contradiction)return {...v,verdict:'conflicting',reasons:[...v.reasons,'The preserved sensor evidence contains a disagreement.']};if((f.confidence.level==='low'||f.classification==='uncertain')&&v.verdict==='supported')return {...v,verdict:'partially_supported',reasons:[...v.reasons,'Low visual support cannot pass as fully supported.']};return v;});
}
export function gateFindings(bundle:CandidateBundle,validations:EvidenceValidation[]):CandidateBundle{return {...bundle,findings:bundle.findings.map(f=>{const v=validations.find(v=>v.findingId===f.id);return !v||v.verdict!=='supported'?{...f,classification:'uncertain',confidence:{...f.confidence,level:v?.verdict==='partially_supported'?'medium':'low'},limitations:[...f.limitations,...(v?.reasons||['No validation verdict'])]}:f;})};}
export function validateSynthesis(value:unknown,bundle:CandidateBundle,verdicts:EvidenceValidation[]){
 const v=object(value);const answer=text(v.directAnswer);const uncertainties=strings(v.uncertainties);const supported=verdicts.filter(v=>v.verdict==='supported').length;
 return {directAnswer:supported?answer:'The available evidence does not support a definitive conclusion. '+bundle.findings.filter(f=>verdicts.find(v=>v.findingId===f.id)?.verdict==='partially_supported').map(f=>'Possible interpretation: '+f.statement).join(' '),uncertainties:[...uncertainties,...verdicts.filter(v=>v.verdict!=='supported').flatMap(v=>v.reasons)],nextQuestion:typeof v.nextQuestion==='string'?v.nextQuestion:''};
}
export function refineExisting(question:string,previous?:MissionResult):MissionResult|null{
 if(!previous||!/\b(only|filter|show)\b/i.test(question)||!/\b(highest|high.confidence|high.support)\b/i.test(question))return null;
 const construction=/construction|built|settlement|building/i.test(question);
 const findings=previous.findings.filter(f=>f.confidence.level==='high'&&previous.validations.find(v=>v.findingId===f.id)?.verdict==='supported'&&(!construction||/construct|built|building|settlement/i.test(f.title+' '+f.category+' '+f.statement)));
 const ids=new Set(findings.flatMap(f=>f.evidenceIds));return {...previous,findings,evidenceItems:previous.evidenceItems.filter(e=>ids.has(e.id)),validations:previous.validations.filter(v=>findings.some(f=>f.id===v.findingId)),crossSensorAssessment:previous.crossSensorAssessment.filter(c=>c.evidenceIds.some(id=>ids.has(id))),directAnswer:findings.length?`Showing ${findings.length} previously supported finding${findings.length===1?'':'s'} with high AI-assessed visual support.`:'No previous findings meet that evidence-strength filter.',trace:[...previous.trace,{timestamp:new Date().toISOString(),stepId:'refine',step:'Refine existing findings',purpose:question,inputs:[],provider:'SatQuery local finding filter',status:'completed',summary:`${findings.length} existing findings selected; no model call.`}]};
}
