from enum import Enum


class TaskFamily(str, Enum):
    SINGLE_VQA = "SINGLE_VQA"
    SINGLE_GROUNDING = "SINGLE_GROUNDING"
    SINGLE_CAPTION = "SINGLE_CAPTION"
    TEMPORAL_CHANGE = "TEMPORAL_CHANGE"
    TEMPORAL_CHANGE_VQA = "TEMPORAL_CHANGE_VQA"
    OPTICAL_SAR_ANALYSIS = "OPTICAL_SAR_ANALYSIS"
    UNKNOWN = "UNKNOWN"


class AnalysisStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    FAILED = "FAILED"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"


class EvidenceVerdict(str, Enum):
    SUPPORTED = "supported"
    PARTIALLY_SUPPORTED = "partially_supported"
    INSUFFICIENT = "insufficient"
    CONFLICTING = "conflicting"
